### ISSUE TITLE
Each run finishes with an error (Allen 1.0.0)

### ISSUE THREAD

**Issue by MichalMalyska** [dhruvdcoder/wandb-allennlp#10]
Every run using the wandb_allennlp --subcommand=train always end with an error with TeeHandler

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1172, in _atexit_cleanup
    self._on_finish()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1292, in _on_finish
    self._console_stop()  # TODO: there's a race here with jupyter console logging
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1203, in _console_stop
    self._restore()
  File "/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1140, in _restore
    self._out_redir.uninstall()
  File "/opt/conda/lib/python3.7/site-packages/wandb/lib/redirect.py", line 207, in uninstall
    self._redirect(to_fd=self._old_fp.fileno(), close=True)
  File "/opt/conda/lib/python3.7/site-packages/wandb/lib/redirect.py", line 161, in _redirect
    fp.close()
AttributeError: 'TeeHandler' object has no attribute 'close'

**Comment by dhruvdcoder** [comment]
Seems like a `wandb` issue. Can you give a minimal example to reproduce the issue?

**Comment by MichalMalyska** [comment]
It was indeed a wandb issue, it was fixed in https://github.com/wandb/client/pull/1327, and will be in the next release.
